const ADMIN_PIN = process.env.ADMIN_PIN || '2029';

// All 178 listings embedded as seed data
const LISTINGS = [
{
"id": "L-01",
"name": "Vicente LLP — Psychedelics & Emerging Therapies",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Full-service psychedelic law — regulatory, corporate, licensing, policy, IP",
"svc": "Full-service psychedelic law: DEA/state licensing, corporate formation, regulatory compliance, policy advocacy, litigation, IP. Acquired Emerge Law Group's Oregon attorneys (December 2025). Joshua Kap",
"price": "Custom quote ($10K+/year)",
"note": "",
"url": ""
},
{
"id": "L-02",
"name": "Emerge Law Group",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Oregon psilocybin licensing; cannabis and emerging industries",
"svc": "Primary drafters of Oregon Measure 109 / Psilocybin Services Act (Dave Kopilak). Five core psychedelic attorneys transitioned to Vicente LLP's Portland office December 2025. Emerge remains active for ",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-03",
"name": "Harris Sliwoski LLP",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Psychedelic regulatory law; cannabis; international controlled substances",
"svc": "Broad psychedelics regulatory and business law. Runs a dedicated Psychedelics Law Blog. Four attorneys named in Top 200 Global Psychedelic Lawyers Guide. Confirmed cannabis banking client: Salal Credi",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-04",
"name": "Plant Medicine Law Group LLP",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Equity-focused psychedelic regulatory law — VERIFY STATUS BEFORE ENGAGING",
"svc": "Founded November 2020 by Adriana Kertzer, Hadas Alterman, and Serena Wu. Adriana Kertzer became sole proprietor December 2022. Hadas Alterman now at Ritter Spencer Cheng PLLC. Firm served psychedelic ",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-05",
"name": "Hadas Alterman — Ritter Spencer Cheng PLLC",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Psychedelic regulatory law — equity-focused; state licensing; drug development",
"svc": "Co-founder of Plant Medicine Law Group (now at Ritter Spencer Cheng PLLC). Served on Oregon Psilocybin Advisory Board (Measure 109) and Colorado Natural Medicine Advisory Board (Proposition 112). Advi",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-06",
"name": "Clark Howell LLP",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Indigenous-aligned nonprofit law; psychedelic governance",
"svc": "California-based women-led firm. General Legal Counsel to Chacruna Institute. Founding partner Ariel Clark is enrolled member of the Grand Traverse Band of Ottawa &amp; Chippewa Indians and co-founder",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-07",
"name": "Zuber Lawler",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Full-service psychedelic and cannabis law; corporate; IP",
"svc": "Full-service cannabis and psychedelics law with offices nationwide. Managing Partner Tom Zuber named in Top 200 Global Psychedelic Lawyers Guide. Wonderland Miami 2022 exhibitor. Corporate, M&amp;A, I",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-08",
"name": "Terrapin Legal",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Boutique full-service psychedelic law; RFRA; DEA licensing; nonprofit governance",
"svc": "Full-service psychedelic law: regulatory compliance, DEA/FDA/state licensing, nonprofit governance, First Amendment and RFRA counsel for religious and entheogenic organizations, clinics, and researche",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-09",
"name": "McAllister Law Office",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Psychedelic and cannabis regulatory law; RFRA; DEA licensing",
"svc": "Pioneer psychedelic law firm serving religious practitioners, therapists, ketamine clinics, pharmaceutical companies, and nonprofit orgs. DEA licensure for Schedule I manufacturing, state program comp",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-10",
"name": "Husch Blackwell — Psychedelics & Emerging Therapies",
"tier": "TIER 1",
"cat": "Legal",
"sub": "DEA licensing; clinical trials; FDA regulatory; Am Law 100",
"svc": "First Am Law 100 firm with dedicated Psychedelics and Emerging Therapies practice. Co-led by Kimberly Chew (scientist-turned-attorney) and Karen Luong. Five attorneys in Top 200 Guide. DEA registratio",
"price": "Custom quote ($10K+/year; Am Law 100 pricing)",
"note": "",
"url": ""
},
{
"id": "L-11",
"name": "Phillips Lytle LLP — Psychedelics & Mental Health Therapies",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Life sciences; FDA regulatory; Am Law 200",
"svc": "FDA regulatory, pharmaceutical product liability, entity formation, IRB protocols, and clinical-trial/informed-consent counsel. Practice co-led by Lisa L. Smith and Kyle W. Mack, PharmD. Lisa L. Smith",
"price": "Custom quote ($10K+/year)",
"note": "",
"url": ""
},
{
"id": "L-12",
"name": "Kathryn Tucker, JD — End of Life Liberty Project / NPA",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Patient rights; end-of-life law; Right to Try; litigation",
"svc": "Nation's leading attorney on psychedelic access at end of life. Executive Director, End of Life Liberty Project. Special Advocacy Advisor, National Psychedelics Association. Founding Board Member, Psy",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-13",
"name": "Dykema — Psychedelic Regulatory & Employment",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Regulatory; employment law; psychedelic businesses",
"svc": "National full-service firm with psychedelic regulatory and employment law practice via partner Brett M. Gelbord, named in Top 200 Global Psychedelic Lawyers Guide.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-14",
"name": "Guidant Law (Arizona)",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Sacramental use; indigenous plant medicine; Arizona psychedelic law",
"svc": "Arizona psychedelic counsel. Gary Smith named in Top 200 Guide two consecutive years. Author of Psychedelica Lex. Documented multi-racial peyote church client.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-15",
"name": "Sick Legal — Entheogen Advisory Practice",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Boutique entheogen law; RFRA; religious organizations; retreat centers",
"svc": "Corporate formation, regulatory guidance, and strategic counsel for religious organizations with sacramental psychedelic practice, clinical research programs, retreat centers, and policymakers. RFRA/F",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-16",
"name": "Aird & Berlis LLP (Toronto)",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Canadian psychedelic biotech; life sciences; corporate",
"svc": "Canadian life-sciences and corporate firm. Four attorneys named in Top 200 Global Psychedelic Lawyers Directory 2025: Elliot Altshuler, Nida Kharazmi, Tristan Merk, Charles Sanders.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-17",
"name": "Hartney Law (Colorado)",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Colorado psychedelic law; governance; ethics",
"svc": "Colorado-based psychedelic law with legal, ethical, and governance focus for psychedelic operators. Named in Top 200 Global Psychedelic Lawyers Guide. Martha Hartney profile confirmed.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-18",
"name": "Hoots Law",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Psychedelic religious-use law; sacramental communities",
"svc": "Boutique practice: psychedelic religious-use legal work for sacramental and ceremonial communities. Allison Hoots named in Top 200 Global Psychedelic Lawyers Guide.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-19",
"name": "Antithesis Law (Jodi Green)",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Psychedelic startups; corporate formation; contracts; regulatory",
"svc": "Corporate formation, contracts, and regulatory compliance for psychedelic startups and organizations. Founded by Jodi Green, PBA board member.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-20",
"name": "Calyx Law LLP",
"tier": "TIER 1",
"cat": "Legal",
"sub": "Nonprofit governance; corporate formation; regulatory; IP",
"svc": "Corporate and transactional support for nonprofits, PBCs, and psychedelic sector companies. Entity formation, licensing, regulatory compliance, M&amp;A, IP. Co-founder Ariel Clark is PBA co-founder an",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "L-21",
"name": "Kleinfeld, Kaplan & Becker LLP",
"tier": "TIER 2",
"cat": "Legal",
"sub": "Psychedelic and cannabis industry accounting",
"svc": "CPA firm in Southern Oregon specializing in psychedelic and cannabis industry accounting. Tax planning, 280E/psilocybin tax guidance, multi-state compliance, audit representation. Featured on Healing ",
"price": "Custom quote (boutique mid-range)",
"note": "",
"url": ""
},
{
"id": "A-02",
"name": "MNP LLP (Toronto)",
"tier": "TIER 1",
"cat": "Accounting & Finance",
"sub": "Canadian professional services; psychedelic biotech; nonprofit accounting",
"svc": "Canada's third-largest professional services firm (8,000+ employees). Cannabis and psychedelic biotech accounting, audit, and advisory. Sponsor of Wonderland Miami 2022.",
"price": "Custom quote ($10K+/year)",
"note": "",
"url": ""
},
{
"id": "A-03",
"name": "TreeStar Solutions",
"tier": "TIER 1",
"cat": "Accounting & Finance",
"sub": "Psychedelic and plant medicine industry accounting; California",
"svc": "Chico, CA accounting firm explicitly positioning for psychedelic-space organizations. Tax planning, entity structuring, bookkeeping, payroll, grant funding support, HIPAA-compliant system guidance for",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "A-04",
"name": "Accounting — Additional Vendors Under Research",
"tier": "TIER 2",
"cat": "Accounting & Finance",
"sub": "Medical malpractice and professional liability — psychedelic-specific",
"svc": "TheraCover™ is the first medical malpractice/professional liability insurance program purpose-built for legal psychedelic-assisted therapy, launched December 2023. Covers doctors, psychiatrists, clini",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "I-02",
"name": "Enthea (Third-Party Benefits Administrator)",
"tier": "TIER 1",
"cat": "Insurance",
"sub": "Employer-sponsored psychedelic therapy benefits; TPA",
"svc": "Licensed TPA of employer-sponsored benefits covering ketamine-assisted psychotherapy (KAP). Builds credentialed clinician network; processes claims; handles utilization management. Osmind-integrated. ",
"price": "$30–$200/employee/year",
"note": "",
"url": ""
},
{
"id": "I-03",
"name": "Oath Insurance",
"tier": "TIER 1",
"cat": "Insurance",
"sub": "Specialty insurance broker — psilocybin service centers and facilitators",
"svc": "Specialty broker explicitly marketing to psilocybin operators: general liability, professional liability, medical malpractice, property, business auto, and cyber for psilocybin service centers, indivi",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "I-04",
"name": "NFP (now an Aon company)",
"tier": "TIER 1",
"cat": "Insurance",
"sub": "National insurance brokerage — professional and product liability",
"svc": "National brokerage with documented psychedelic professional and product liability lines. Named in HAF vendor document.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "I-05",
"name": "AssuredPartners",
"tier": "TIER 1",
"cat": "Insurance",
"sub": "National insurance brokerage — psychedelic businesses",
"svc": "National retail brokerage with named contact for psilocybin clients. Named in HAF vendor document.",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "I-06",
"name": "AlphaRoot",
"tier": "TIER 1",
"cat": "Insurance",
"sub": "Grant discovery and pipeline management",
"svc": "All-in-one platform combining funder discovery and grant pipeline management. AI-powered funder matching, deadline tracking, application status management, and reporting. Designed for nonprofits apply",
"price": "$179–$299/month",
"note": "",
"url": ""
},
{
"id": "G-02",
"name": "GrantHub (by Foundant)",
"tier": "TIER 2",
"cat": "Grant Management",
"sub": "Grant deadline tracking and pipeline management",
"svc": "Simplified grant management: deadline tracking, task management, and application status. Lower cost than Instrumentl; simpler UI.",
"price": "$99/month",
"note": "",
"url": ""
},
{
"id": "G-03",
"name": "Salesforce Nonprofit Success Pack — Power of Us",
"tier": "TIER 2",
"cat": "Grant Management",
"sub": "Credit union — cannabis and emerging-industry business banking; Oregon",
"svc": "Salem, Oregon credit union and the first financial institution in Oregon to open cannabis business accounts (2014). Rachel Pross (Chief Risk Officer) testified to Congress in favor of the SAFE Banking",
"price": "Standard credit union business account fees",
"note": "",
"url": ""
},
{
"id": "B-02",
"name": "Salal Credit Union",
"tier": "TIER 1",
"cat": "Banking",
"sub": "Credit union — cannabis and emerging-industry business banking; Oregon and Washington",
"svc": "Washington State-based credit union with documented cannabis business banking practice in Oregon. Confirmed Harris Sliwoski client for cannabis banking. Business checking, savings, lending, and cash m",
"price": "Standard credit union business account fees",
"note": "",
"url": ""
},
{
"id": "B-03",
"name": "Green Check Verified",
"tier": "TIER 2",
"cat": "Banking",
"sub": "Fintech — cannabis and emerging-industry banking matchmaking",
"svc": "Fintech platform connecting cannabis and emerging-industry businesses with banking partners. Provides compliance technology and banking matchmaking for businesses in regulated industries. As psilocybi",
"price": "Custom quote (per transaction / subscription)",
"note": "",
"url": ""
},
{
"id": "B-SAFER",
"name": "SAFER Banking Act — Policy Context",
"tier": "REF",
"cat": "Banking",
"sub": "OHA + HECC + DORA approved; first cohort April 2021; most alumni-led service centers",
"svc": "Launched April 2021; produced 17 cohorts. Graduates became the nation's first licensed psilocybin facilitators. Over 33 of Oregon's licensed service centers operated by alumni. First Colorado DORA-lic",
"price": "$9,000–$12,000 total (tuition range; confirm current pricing)",
"note": "",
"url": ""
},
{
"id": "FT-02",
"name": "InnerTrek",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA + HECC + DORA approved; founded by architect of Measure 109",
"svc": "Founded by Tom Eckert, the architect of Oregon's Measure 109 (the Psilocybin Services Act itself). OHA, HECC, and DORA approved. 150+ hours of core didactic training and 40 hours of supervised practic",
"price": "Contact for current pricing (field range: $8,000–$12,000)",
"note": "",
"url": ""
},
{
"id": "FT-03",
"name": "Naropa University — Center for Psychedelic Studies",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA + DORA approved; accredited university program; contemplative approach",
"svc": "Psilocybin Facilitator Training (PFT) certificate through the Naropa Center for Psychedelic Studies (NCPS). OHA and Colorado DORA approved. Announced July 2024 as one of the first fully state-approved",
"price": "Contact for current pricing; university-scale pricing with scholarship access",
"note": "",
"url": ""
},
{
"id": "FT-04",
"name": "Synaptic Institute",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA + HECC approved; hybrid; small cohort model; Portland practicum",
"svc": "Donor management platform for individual giving programs. Donor database, giving history, email, donation forms, and retention analytics.",
"price": "$125–$599/month (scales by donor database size)",
"note": "",
"url": ""
},
{
"id": "D-02",
"name": "Little Green Light",
"tier": "TIER 2",
"cat": "Fundraising CRM",
"sub": "",
"svc": "Lightweight, affordable donor management: donor records, gift tracking, pledge management, acknowledgment letters, and basic email.",
"price": "$45–$159/month",
"note": "",
"url": ""
},
{
"id": "D-03",
"name": "DonorPerfect",
"tier": "TIER 2",
"cat": "Fundraising CRM",
"sub": "",
"svc": "Donor database, online donation forms, recurring-gift management, automated workflows, reporting. Employee-owned — not PE-consolidated.",
"price": "$99/month and up; see pricing guide",
"note": "",
"url": ""
},
{
"id": "D-04",
"name": "Bonterra Guided Fundraising (formerly Network for Good)",
"tier": "TIER 2",
"cat": "Fundraising CRM",
"sub": "",
"svc": "Donor management CRM with built-in personal coaching, fundraising pages, email outreach, and donor segmentation. Part of Bonterra (PE consolidation of Network for Good, EveryAction, Salsa).",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "R-01",
"name": "REDCap (Research Electronic Data Capture) — Vanderbilt University",
"tier": "TIER 1",
"cat": "Research Infrastructure",
"sub": "Free, open-source, HIPAA-compliant research data platform",
"svc": "Gold standard for IRB-accepted research data. Standard platform at Johns Hopkins, NYU, and UC Berkeley psychedelic research centers. Free for orgs affiliated with REDCap consortium member institutions",
"price": "Free for consortium affiliates; hosting costs vary",
"note": "",
"url": ""
},
{
"id": "R-02",
"name": "Qualtrics (XM Platform)",
"tier": "TIER 2",
"cat": "Research Infrastructure",
"sub": "Commercial survey and experience management platform",
"svc": "Commercial survey and experience management. HIPAA-compliant version available. More accessible to non-technical users than REDCap. Used broadly in behavioral health and clinical research.",
"price": "$1,500–$5,000+/year; HIPAA-compliant tier higher",
"note": "",
"url": ""
},
{
"id": "T-01",
"name": "Osmind",
"tier": "TIER 1",
"cat": "Technology",
"sub": "Purpose-built EHR for psychedelic-assisted therapy, ketamine, SPRAVATO, TMS",
"svc": "Psychedelic-specific charting templates, 30+ validated rating scales, REMS workflow, HIPAA-compliant patient app, e-prescribing, billing, prior-auth automation. Network of 800+ independent psychiatry ",
"price": "Custom quote ($1K–$10K+/year)",
"note": "",
"url": ""
},
{
"id": "T-02",
"name": "Wavepaths",
"tier": "TIER 1",
"cat": "Technology",
"sub": "AI-generated functional music for psychedelic-assisted therapy sessions",
"svc": "AI-generated functional music for psychedelic-assisted therapy sessions. Osmind-integrated. Founded by Mendel Kaelen (former researcher, Imperial College London). Designed specifically for therapeutic",
"price": "Custom quote",
"note": "",
"url": ""
},
{
"id": "T-03",
"name": "FieldPrint",
"tier": "TIER 1",
"cat": "Technology",
"sub": "Fingerprint-based background checks — required by OHA for psilocybin facilitator licensure",
"svc": "Fingerprint-based background-check vendor required by Oregon Health Authority for psilocybin facilitator licensure. Named directly in the OHA Psilocybin Facilitator License Application Guide. Private ",
"price": "Per-transaction fee",
"note": "",
"url": ""
},
{
"id": "T-04",
"name": "Google Workspace for Nonprofits",
"tier": "TIER 1",
"cat": "Technology",
"sub": "Free Google productivity tools for qualifying 501(c)(3)s",
"svc": "Free Gmail, Drive, Docs, Sheets, Slides, Meet, and Forms for qualifying 501(c)(3)s. Up to 300 users on Business Starter. Strong case for small psychedelic nonprofits with limited IT budgets.",
"price": "Free; $3/user/month for Business Standard",
"note": "",
"url": ""
},
{
"id": "T-05",
"name": "Microsoft 365 for Nonprofits",
"tier": "TIER 1",
"cat": "Technology",
"sub": "Free Microsoft tools for qualifying 501(c)(3)s",
"svc": "Free Outlook, Teams, Word, Excel, SharePoint, OneDrive for qualifying 501(c)(3)s (up to 10 users on Business Basic). Strong for orgs that need Windows-native tool stack or have Board members on Outloo",
"price": "Free; $3/user/month for Business Standard",
"note": "",
"url": ""
},
{
"id": "T-06",
"name": "SimplePractice",
"tier": "TIER 2",
"cat": "Technology",
"sub": "Behavioral health practice management — scheduling, telehealth, billing",
"svc": "All-in-one behavioral health practice management: scheduling, telehealth, billing, secure messaging, HIPAA-compliant storage. Popular for individual facilitators and small practices. Not psychedelic-s",
"price": "$69–$149/month",
"note": "",
"url": ""
},
{
"id": "T-07",
"name": "TherapyNotes",
"tier": "TIER 2",
"cat": "Technology",
"sub": "Cloud-based EHR and practice management for behavioral health",
"svc": "Cloud-based EHR and practice management: scheduling, clinical documentation, billing, telehealth, and e-prescribing. Strong reputation in behavioral health for reliability and customer service. Not ps",
"price": "$59–$99/month",
"note": "",
"url": ""
},
{
"id": "H-01",
"name": "Rippling",
"tier": "TIER 2",
"cat": "HR & People Ops",
"sub": "All-in-one workforce management; multi-state EOR; device management",
"svc": "Payroll, benefits, device management, compliance, Employer of Record (EOR) capability for multi-state hiring. Strong for orgs hiring across OR, CO, and other states simultaneously. HR, IT, and finance",
"price": "~$8/employee/month base + modules",
"note": "",
"url": ""
},
{
"id": "H-02",
"name": "Gusto",
"tier": "TIER 2",
"cat": "HR & People Ops",
"sub": "Payroll, benefits, and basic HR for small nonprofits",
"svc": "Payroll, benefits, and basic HR. Multi-state payroll, contractor payments (1099), time tracking. Simpler and less expensive than Rippling. Good starting point for orgs under 20 employees.",
"price": "$40/month + $6/person/month",
"note": "",
"url": ""
},
{
"id": "H-03",
"name": "TriNet (PEO)",
"tier": "TIER 2",
"cat": "HR & People Ops",
"sub": "Co-employment PEO for nonprofits — pooled benefits, compliance, EOR",
"svc": "Co-employment PEO: payroll, HR compliance, benefits administration, workers comp, employer-of-record. Access to Fortune 500-level benefits through pooled purchasing. Good for nonprofits that cannot se",
"price": "~$150–$200/employee/month fully loaded",
"note": "",
"url": ""
},
{
"id": "H-04",
"name": "Justworks (PEO)",
"tier": "TIER 2",
"cat": "HR & People Ops",
"sub": "PEO for small nonprofits — transparent pricing, strong benefits access",
"svc": "PEO: payroll, pooled health insurance, HR compliance, time tracking, 24/7 HR advisory. More transparent pricing than TriNet. Particularly strong for orgs 5–50 employees.",
"price": "$59–$99/month/employee",
"note": "",
"url": ""
},
{
"id": "C-01",
"name": "KCSA Strategic Communications",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Strategic communications; investor relations; capital-markets support for psychedelic orgs",
"svc": "Strategic communications, investor relations, and capital-markets support for psychedelic and CNS organizations. Six-year documented partnership with MAPS. PRNEWS Platinum Award for Best Conference Ma",
"price": "$10K+/year (agency retainer)",
"note": "",
"url": ""
},
{
"id": "C-02",
"name": "Integration Communications",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Specialist psychedelic communications boutique — PR, media, branding",
"svc": "PR, media relations, crisis management, media training, brand strategy, SEO. Founded by Brad Burge, formerly MAPS Director of Strategic Communications (2009–2020) and producer of Psychedelic Science 2",
"price": "$1K–$10K/year",
"note": "",
"url": ""
},
{
"id": "C-03",
"name": "Capitol Counsel LLC",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Federal lobbying and government affairs for psychedelic policy",
"svc": "Bipartisan federal lobbying, public-policy advocacy, government affairs counsel. Registered federal lobbyist for Healing Advocacy Fund on state-legal psilocybin therapy (LDA filing, April 15, 2023). H",
"price": "$10K+/year; HAF disclosed $40,000/quarter in 2023",
"note": "",
"url": ""
},
{
"id": "C-04",
"name": "Lucid News",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Independent psychedelic sector news — policy, science, business, culture",
"svc": "Independent psychedelic sector news: policy, science, business, culture. Official media partner of Horizons conference. This is a media outlet, not a PR vendor — useful as a pitch target for earned me",
"price": "Free (pitch-based editorial)",
"note": "",
"url": ""
},
{
"id": "C-05",
"name": "Psychedelic Alpha",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Data-driven psychedelic news and analysis — global coverage",
"svc": "Independent data-driven psychedelic news, regulatory tracking, market intelligence. Global scope. High credibility with field insiders, investors, and policy researchers. Useful as an earned media tar",
"price": "Free (pitch-based editorial); newsletter subscription available",
"note": "",
"url": ""
},
{
"id": "C-06",
"name": "NisonCo PR",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "PR, SEO, and content marketing for cannabis and psychedelic clients",
"svc": "PR, SEO, and content marketing for cannabis and psychedelic clients. Documented placements in Huffington Post, Inc., Yahoo Finance, Forbes, Business Insider, High Times. Cannabis-sector since 2013; ex",
"price": "$1K–$10K/year",
"note": "",
"url": ""
},
{
"id": "C-07",
"name": "Durée & Company",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "Strategic PR, content marketing, branding; psychedelics and neurowellness",
"svc": "Strategic PR, content marketing, branding, and media outreach for psychedelic and neurowellness organizations. Operates psychedelicpr.com dedicated microsite. Documented placements in WSJ, Forbes, Fox",
"price": "$10K+/year",
"note": "",
"url": ""
},
{
"id": "C-08",
"name": "RN Collins — AI Strategy & Regulatory Intelligence",
"tier": "TIER 1",
"cat": "Community Infrastructure",
"sub": "AI strategy and consulting for psychedelic health organizations",
"svc": "AI strategy and consulting for psychedelic health organizations. AI content system development, grant reporting automation, multi-state regulatory compliance tracking, stakeholder communication templa",
"price": "$2,500–$21,000 per engagement; retainer $1,500–$3,500/month",
"note": "CONFLICT DISCLOSURE: RN Collins is the founder and editor of Psych Ops. This is a self-reported listing, clearly labeled per Psych Ops confl",
"url": ""
},
{
"id": "E-01",
"name": "Momentum Events",
"tier": "TIER 1",
"cat": "Education & Training",
"sub": "Major experiential event production; produced Psychedelic Science 2025",
"svc": "Major experiential event production (Bonnaroo, Outside Lands). Produced MAPS Psychedelic Science 2025 in Denver (June 2025). Full-service conference production including event design, marketing, regis",
"price": "Custom quote (project-based)",
"note": "",
"url": ""
},
{
"id": "E-02",
"name": "Superfly",
"tier": "TIER 1",
"cat": "Education & Training",
"sub": "Full conference production; co-produced Psychedelic Science 2023",
"svc": "Full conference production: event design, marketing, registration, exhibit hall management, affiliated programming. Co-produced MAPS Psychedelic Science 2023 (12,000+ attendees, Denver, June 2023).",
"price": "Custom quote (project-based)",
"note": "",
"url": ""
},
{
"id": "E-03",
"name": "Horizons Center PBC",
"tier": "TIER 1",
"cat": "Education & Training",
"sub": "Produces Horizons NYC and Horizons Northwest — flagship annual psychedelic conferences",
"svc": "Produces Horizons NYC (longest-running annual psychedelic conference in the world; New York Academy of Medicine and Cooper Union Great Hall) and Horizons Northwest (Portland, OR, in partnership with S",
"price": "Custom (conference exhibition rates vary)",
"note": "",
"url": ""
},
{
"id": "TA-01",
"name": "TransPerfect",
"tier": "TIER 2",
"cat": "Translation & Language",
"sub": "Translation in 170+ languages; medical/clinical interpretation; world largest LSP",
"svc": "Translation in 170+ languages; medical/clinical interpretation (phone, video, in-person); informed-consent and clinical-trial document translation; ASL; closed captioning. World largest language servi",
"price": "Project-based ($1K–$10K+); OPI per-minute",
"note": "",
"url": ""
},
{
"id": "TA-02",
"name": "LanguageLine Solutions",
"tier": "TIER 2",
"cat": "Translation & Language",
"sub": "On-demand phone and video interpretation; 240+ languages; HIPAA-compliant",
"svc": "On-demand phone and video interpretation in 240+ languages. Medical and behavioral-health specialization. HIPAA-compliant. 24/7 availability. Standard vendor for healthcare and clinical settings needi",
"price": "$1–$3/minute (phone OPI); under $1K/year for low-volume nonprofits",
"note": "",
"url": ""
},
{
"id": "TA-03",
"name": "Northwest Translations",
"tier": "TIER 2",
"cat": "Translation & Language",
"sub": "ISO 17100:2015-certified translation; clinical research specialization; 100+ languages",
"svc": "ISO 17100:2015-certified translation in 100+ languages. Clinical research, healthcare, and life science specialization. Documented use at University of Colorado Anschutz clinical research programs.",
"price": "Project-based ($1K–$10K+/year)",
"note": "",
"url": ""
},
{
"id": "CM-01",
"name": "H.C. Wainwright & Co.",
"tier": "TIER 1",
"cat": "Capital Markets",
"sub": "Specialty life-sciences investment bank; led most psychedelic public offerings 2020–2024",
"svc": "Specialty life-sciences investment bank. Lead or co-manager on most psychedelic public offerings (IPOs, PIPEs, ATMs) 2020–2024. Official Banking Sponsor at Wonderland Miami 2022. Equity research, inst",
"price": "Investment banking fees (standard 5–7% underwriting)",
"note": "",
"url": ""
},
{
"id": "RC-01",
"name": "RN Collins — Data Governance & Regulatory Intelligence",
"tier": "TIER 1",
"cat": "Research Collaborators",
"sub": "Data governance; Oregon/Colorado compliance; Medicaid evidence architecture",
"svc": "Strategic and compliance-layer consulting for state psilocybin programs, pilot research initiatives, and nonprofits building toward Medicaid reimbursement. Data governance policy design; regulatory co",
"price": "$3,500–$21,000 per engagement",
"note": "CONFLICT DISCLOSURE: Self-listed by Psych Ops founder RN Collins.",
"url": ""
},
{
"id": "CRO-01",
"name": "KGK Science",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Canadian CRO with documented psychedelic clinical trial work",
"svc": "Canadian CRO with documented psychedelic clinical trial work. Full CRO services: protocol development, site selection, data management, biostatistics, regulatory submissions. Gold exhibitor at Wonderl",
"price": "Custom quote (project-based)",
"note": "",
"url": ""
},
{
"id": "CRO-02",
"name": "Segal Trials",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Multi-site clinical research organization with psychedelic trial site network",
"svc": "Multi-site clinical research organization with psychedelic trial site network. Gold exhibitor at Wonderland Miami 2022. Provides trial site infrastructure for clinical-trial sponsors across multiple t",
"price": "Custom quote (project-based)",
"note": "",
"url": ""
},
{
"id": "BK-01",
"name": "Salal Credit Union",
"tier": "TIER 3",
"cat": "Banking & Financial Services",
"sub": "Cannabis-friendly credit union — psilocybin unconfirmed",
"svc": "Washington-based credit union providing compliant business banking to cannabis-adjacent businesses under the 2014 FinCEN guidance. Named by Harris Sliwoski as among the few institutions plausibly able to extend services to state-licensed psilocybin businesses. Psilocybin account not yet confirmed.",
"price": "Contact for business account rates",
"note": "Cannabis-confirmed only; verify psilocybin policy directly",
"url": "salalcu.org"
},
{
"id": "BK-02",
"name": "Maps Credit Union",
"tier": "TIER 3",
"cat": "Banking & Financial Services",
"sub": "Oregon cannabis-friendly credit union",
"svc": "Oregon credit union with a long-standing cannabis banking program under FinCEN guidance. Flagged as a plausible candidate to bank Oregon-licensed psilocybin service centers. Unrelated to MAPS (Multidisciplinary Association for Psychedelic Studies) nonprofit. No confirmed psilocybin account.",
"price": "Contact for business banking rates",
"note": "Name coincidence with MAPS nonprofit — unrelated entities",
"url": "mapscu.com"
},
{
"id": "BK-03",
"name": "Wauna Credit Union",
"tier": "TIER 3",
"cat": "Banking & Financial Services",
"sub": "Northwest Oregon cannabis credit union",
"svc": "Small Oregon credit union serving cannabis businesses in the northwest corner of the state; cited as a potential candidate for psilocybin banking infrastructure.",
"price": "Contact for rates",
"note": "Very limited geographic footprint",
"url": "waunafcu.org"
},
{
"id": "BK-04",
"name": "Central Willamette Credit Union",
"tier": "TIER 3",
"cat": "Banking & Financial Services",
"sub": "Oregon dedicated cannabis business banking",
"svc": "Oregon credit union with a dedicated cannabis business accounts program; relevant infrastructure for regulated psilocybin businesses. Cannabis confirmed on own site; psilocybin policy unconfirmed.",
"price": "Contact for cannabis/emerging-industry business rates",
"note": "Cannabis-confirmed only",
"url": "centralwcu.org/business-banking/cannabis-banking"
},
{
"id": "BK-05",
"name": "Safe Harbor Financial / Abaca",
"tier": "TIER 3",
"cat": "Banking & Financial Services",
"sub": "NASDAQ-listed cannabis fintech / banking-as-a-service",
"svc": "NASDAQ-listed (SHFS) facilitator of compliant banking, lending, payments, and treasury for regulated cannabis industries via FDIC/NCUA partner institutions. Acquired fintech Abaca in November 2022. Operating in 40+ US states. Spun out of Partner Colorado Credit Union. Most scalable existing model for psychedelic business banking.",
"price": "Underwriting and account fees vary by state",
"note": "Cannabis-focused; psilocybin extension not yet confirmed",
"url": "shfinancial.org"
},
{
"id": "CM-01",
"name": "Palo Santo",
"tier": "TIER 1",
"cat": "Capital Markets / VC",
"sub": "Dedicated psychedelic VC — $50M fund, Gilgamesh/AbbVie $1.2B exit",
"svc": "Chicago-based VC fund (co-founders Tim Schlidt and Daniel Goldberg) investing exclusively across the psychedelic ecosystem. Closed oversubscribed $50M fund October 2022 with 20+ portfolio companies including Gilgamesh Pharmaceuticals (AbbVie $1.2B acquisition), Delix Therapeutics, Beckley Psytech, Bexson Biomedical, Tactogen.",
"price": "Equity investment; direct to portfolio companies",
"note": "",
"url": "palosanto.vc"
},
{
"id": "CM-02",
"name": "Negev Capital",
"tier": "TIER 1",
"cat": "Capital Markets / VC",
"sub": "Psychedelic medicine investment fund",
"svc": "Investment fund focused exclusively on psychedelic medical intervention and drug development. Provides capital to early-stage companies developing novel psychedelic-based therapeutics and delivery infrastructure.",
"price": "Equity investment",
"note": "",
"url": "negev.capital"
},
{
"id": "CM-03",
"name": "Iter Investments",
"tier": "TIER 1",
"cat": "Capital Markets / VC",
"sub": "Early-stage psychedelic ecosystem VC — global",
"svc": "Global investment firm partnering with early-stage companies across the psychedelic ecosystem to transform mental and behavioral health. Specializes in startup, early-stage, and Series A investments across therapeutics, services, and enabling technologies.",
"price": "Equity investment",
"note": "",
"url": "iterinvestments.com"
},
{
"id": "CM-04",
"name": "PsyMed Ventures",
"tier": "TIER 1",
"cat": "Capital Markets / VC",
"sub": "Psychedelic + precision psychiatry VC",
"svc": "Early-stage investment firm focused on companies combining psychedelics, precision psychiatry, and digital health tools to advance mental health outcomes. Targets therapeutics and tech-enabled care delivery.",
"price": "Equity investment",
"note": "",
"url": "psymedventures.com"
},
{
"id": "CM-05",
"name": "Noetic Fund",
"tier": "TIER 1",
"cat": "Capital Markets / VC",
"sub": "Canadian early-stage psychedelic VC",
"svc": "Canadian early-stage venture investor targeting psychedelic-medicine mental health solutions. Invests across drug development, therapy platforms, and supporting infrastructure within the Canadian and global psychedelic ecosystem.",
"price": "Equity investment",
"note": "",
"url": "noetic.fund"
},
{
"id": "FT-01",
"name": "InnerTrek",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA/HECC + DORA dual-approved — Oregon & Colorado",
"svc": "Oregon and Colorado dual-approved psilocybin facilitator training program; founded by the architect of Oregon's first legal psilocybin services model. Preparing students for New Mexico's 2027 program. Comprehensive curriculum covering set, setting, safety, and state licensing requirements.",
"price": "Contact for current cohort tuition",
"note": "",
"url": "innertrek.org/psychedelic-facilitator-training"
},
{
"id": "FT-02",
"name": "Changa Institute",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA/HECC + DORA dual-approved — online cohort, $6,799",
"svc": "Oregon OHA/HECC and Colorado DORA approved facilitator training. Approximately 4.5-month online cohort model with synchronous and asynchronous components. Tuition $6,799 with payment plans and Klarna available. Global student base with state-specific licensing preparation.",
"price": "$6,799 (payment plans available)",
"note": "",
"url": "changainstitute.com/programs/oregon-certification"
},
{
"id": "FT-03",
"name": "Leela School",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "OHA/HECC-licensed — 9-month/205-hr, Ashland OR",
"svc": "Oregon Health Authority and HECC-licensed 9-month, 205-hour psilocybin facilitator training program. Online curriculum with two required in-person retreat components in Ashland, Oregon. Rooted in somatic and relational approaches.",
"price": "Contact for current tuition",
"note": "",
"url": "leelaschool.org/psilocybin-facilitator-program"
},
{
"id": "FT-04",
"name": "Numinus — Psilocybin Facilitator Training",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "DORA-approved Colorado + MAPS MDMA experiential partner",
"svc": "DORA-approved Colorado Natural Medicine facilitator training program. Practicum partner: The Center Origin, Denver. MAPS MDMA experiential training partner (Health Canada NUMT1 trial). Broad psychedelic-assisted therapy and KAP training across North America.",
"price": "Contact for program fees",
"note": "",
"url": "numinusnetwork.com/training/colorado-approved-natural-medicine-facilitator-training-program"
},
{
"id": "FT-05",
"name": "Synthesis Institute",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "DORA-approved Colorado — verify operational status",
"svc": "Colorado DORA-approved Practitioner Core Training program (150+ hours). Historically operated legal psilocybin truffle retreats in the Netherlands. Training approval confirmed; operational stability should be independently verified.",
"price": "Contact for current tuition",
"note": "RED FLAG: 2023 financial/operational turmoil reported — verify current status",
"url": "synthesisinstitute.com"
},
{
"id": "FT-06",
"name": "Elemental Psychedelics",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "DORA-approved Colorado — clinical + wellness tracks",
"svc": "Colorado DORA-approved 150-hour mushroom facilitator training program offering both clinical and wellness tracks. Includes practicum and supervision consultation hours required for state licensure.",
"price": "Contact for current tuition",
"note": "",
"url": "elementalpsychedelics.com/mushroomtraining"
},
{
"id": "FT-07",
"name": "CU Denver — Center for Psychedelic Research",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "DORA-approved university-based facilitator training — launched 2025",
"svc": "University of Colorado Denver DORA-approved facilitator training program, launched 2025. Transdisciplinary academic approach to psychedelic facilitation with scientific grounding. Also conducts original research into psychedelic effects and applications.",
"price": "University graduate tuition rates",
"note": "",
"url": "clas.ucdenver.edu/psychedelic-research"
},
{
"id": "FT-08",
"name": "CIIS — Center for Psychedelic Therapies and Research",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Professional certificate — one of the oldest programs, SF/Boston",
"svc": "California Institute of Integral Studies professional certificate in psychedelic-assisted therapies and research. Among the oldest and most-cited programs nationally. Covers pharmacology, research design, ethics, and therapist competencies.",
"price": "Contact for graduate certificate tuition",
"note": "",
"url": "ciis.edu"
},
{
"id": "FT-09",
"name": "BCSP — Certificate in Psychedelic Facilitation (UC Berkeley)",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "9-month/200-hr — advanced healthcare and spiritual-care professionals",
"svc": "Berkeley Center for the Science of Psychedelics 9-month, 200-hour interdisciplinary facilitation training for advanced religious, spiritual-care, and healthcare professionals. Combines scientific training with experiential learning and integrative frameworks.",
"price": "Contact for certificate program fees",
"note": "",
"url": "bcsp.berkeley.edu"
},
{
"id": "FT-10",
"name": "MAPS / Lykos MDMA Therapy Training Program",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "~2,000 clinicians trained; paused during NDA process",
"svc": "Original MDMA-assisted therapy training developed by MAPS/MAPS PBC (now Lykos Therapeutics). Approximately 2,000 clinicians trained through end of 2021 across the US, Canada, Europe, and Israel. Training paused during FDA NDA review process.",
"price": "Contact MAPS PBC for current status",
"note": "Training paused; verify re-enrollment timeline",
"url": "mapspublicbenefit.com"
},
{
"id": "FT-11",
"name": "Mind Medicine Australia — CPAT",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Certificate in Psychedelic-Assisted Therapies — Australia",
"svc": "Mind Medicine Australia Certificate in Psychedelic-Assisted Therapies (CPAT). Online and in-person components across Australia. Designed to prepare mental health professionals for Australia's TGA scheduling change (Schedule 8 approval effective July 2023).",
"price": "Contact for certificate program fees",
"note": "",
"url": "cpat.mindmedicineaustralia.org"
},
{
"id": "FT-12",
"name": "MIND Foundation — Augmented Psychotherapy Training (APT)",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Online + in-person — Germany/Europe",
"svc": "MIND Foundation psychedelic-assisted therapy training available in English and German. Online foundation curriculum with in-person intensive components in Germany and across Europe. Evidence-based, scientifically grounded approach.",
"price": "Contact for program fees",
"note": "",
"url": "mind-foundation.org/apt"
},
{
"id": "FT-13",
"name": "Vancouver Island University — PAT Graduate Certificate",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Online graduate certificate — Canada",
"svc": "Vancouver Island University online graduate certificate in Psychedelic-Assisted Therapies. Designed for licensed mental health professionals. Prepares therapists for emerging psychedelic therapy practice in the Canadian regulatory context.",
"price": "Graduate university tuition",
"note": "",
"url": "hhs.viu.ca/psychedelic-assisted-therapy"
},
{
"id": "FT-14",
"name": "University of Ottawa — Psychedelics & Spirituality Microprogram",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Graduate microprogram — Canada",
"svc": "University of Ottawa graduate microprogram exploring psychedelics and spirituality within academic, clinical, and cultural contexts. Interdisciplinary approach spanning neuroscience, religious studies, ethics, and healthcare.",
"price": "Graduate university tuition",
"note": "",
"url": "catalogue.uottawa.ca"
},
{
"id": "FT-15",
"name": "Naropa University — PAT Certificate",
"tier": "TIER 2",
"cat": "Facilitator Training",
"sub": "Psychedelic-assisted therapies certificate — Colorado",
"svc": "Naropa University psychedelic-assisted therapies professional certificate program in Boulder, Colorado. Online and in-person format rooted in contemplative approaches. Designed for licensed mental health clinicians and integrative health practitioners.",
"price": "Contact for certificate tuition",
"note": "",
"url": "naropa.edu"
},
{
"id": "FT-16",
"name": "Integrative Psychiatry Institute (IPI)",
"tier": "TIER 2",
"cat": "Facilitator Training",
"sub": "Year-long PAT training — online + in-person, Colorado",
"svc": "Integrative Psychiatry Institute year-long psychedelic-assisted therapy training for licensed mental health professionals. Online curriculum with in-person retreat components. Focus on KAP, integration practices, and emerging psilocybin and MDMA frameworks.",
"price": "Contact for year-long program tuition",
"note": "",
"url": "psychiatryinstitute.com"
},
{
"id": "FT-17",
"name": "PRATI — Psychedelic Research and Training Institute",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "Colorado KAP training — Fluence practicum partner",
"svc": "Colorado-based KAP training institute and Fluence practicum partner. Provides supervised clinical training hours for therapists completing Fluence's Colorado DORA-aligned psilocybin facilitation certificate.",
"price": "Contact for training fees",
"note": "",
"url": "prati.org"
},
{
"id": "FT-18",
"name": "Ketamine Training Center",
"tier": "TIER 1",
"cat": "Facilitator Training",
"sub": "KAP training — Dr. Phil Wolfson, various US locations",
"svc": "Ketamine-assisted psychotherapy training founded and led by Dr. Phil Wolfson, author of The Ketamine Papers. In-person and online training for licensed clinicians in KAP protocol delivery, safety, and therapeutic integration.",
"price": "Contact for training fees",
"note": "",
"url": "theketaminetrainingcenter.com"
},
{
"id": "FT-19",
"name": "Psychedelic Somatic Institute",
"tier": "TIER 2",
"cat": "Facilitator Training",
"sub": "In-person training — Colorado, Australia, Europe",
"svc": "Psychedelic Somatic Institute training in the Psychedelic Somatic Interactional Psychotherapy (PSIP) model. Intensive in-person training formats offered in Colorado, Australia, and Europe. Focus on body-centered, trauma-informed approaches.",
"price": "Contact for training fees",
"note": "",
"url": "psychedelicsomatic.org"
},
{
"id": "FT-20",
"name": "ATMA Journey Centers",
"tier": "TIER 2",
"cat": "Facilitator Training",
"sub": "Online intro to psychedelic-assisted psychotherapy — Canada",
"svc": "ATMA Journey Centers online introductory training in psychedelic-assisted psychotherapy frameworks. Canadian-based. Relevant for therapists seeking foundational training before engaging more advanced clinical programs.",
"price": "Contact for course fees",
"note": "",
"url": "atmajourney.com"
},
{
"id": "CR-01",
"name": "Worldwide Clinical Trials",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "CRO for COMPASS COMP360 Phase 2b — NEJM-confirmed, 22 sites/10 countries",
"svc": "Full-service CRO that supervised COMPASS Pathways' pivotal Phase 2b COMP360 synthetic psilocybin trial for treatment-resistant depression (Goodwin et al., NEJM, Nov 3, 2022). Trial enrolled 233 patients across 22 sites in 10 countries. Explicitly acknowledged in NEJM publication.",
"price": "Custom CRO contract",
"note": "Primary source: NEJM doi/10.1056/NEJMoa2206443",
"url": "worldwide.com"
},
{
"id": "CR-02",
"name": "MMS Holdings",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Lykos/MAPS PBC CRO for MDMA PTSD NDA — regulatory/pharmacovigilance",
"svc": "Regulatory strategy, pharmacovigilance, medical writing, and biometrics CRO that served as Lykos Therapeutics (formerly MAPS PBC) partner on the MDMA-assisted therapy PTSD New Drug Application.",
"price": "Custom CRO contract",
"note": "Primary source: mmsholdings.com/maps-pbc-nda-submission",
"url": "mmsholdings.com"
},
{
"id": "CR-03",
"name": "MedAvante-ProPhase (a WCG Company)",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Blinded central rating CRO — COMPASS COMP360 Phase 2b, NEJM-confirmed",
"svc": "Specialized CRO responsible for blinded central MADRS rating in the COMPASS COMP360 Phase 2b trial. Explicitly named in the NEJM publication as the independent rater for the landmark trial.",
"price": "Custom CRO contract",
"note": "Primary source: NEJM doi/10.1056/NEJMoa2206443",
"url": "medavante-prophase.com"
},
{
"id": "CR-04",
"name": "BioPharma Services Inc.",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Full-service CRO — dedicated psychedelics early-phase division, Toronto",
"svc": "Full-service Canadian CRO with a dedicated psychedelics early-phase division. Publishes actively on psilocybin, MDMA, and LSD trial design and Human Abuse Potential (HAP) study challenges.",
"price": "Custom CRO contract",
"note": "",
"url": "biopharmaservices.com"
},
{
"id": "CR-05",
"name": "Clinilabs Drug Development Corp",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "CRO for Cybin CYB003 psilocybin analog Phase I/IIa trial",
"svc": "CNS/psychiatry-specialist CRO selected to run Cybin CYB003 (deuterated psilocybin analog) trial for major depressive disorder. Documented psychedelic-compound trial execution infrastructure.",
"price": "Custom CRO contract",
"note": "",
"url": "clinilabs.com"
},
{
"id": "CR-06",
"name": "ethica CRO",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Full-service global CRO — Mydecine Phase 2A PTSD/MDMA trial",
"svc": "Full-service global CRO engaged by Mydecine Innovations Group to run its Phase 2A PTSD/MDMA trial. Provides clinical trial management, regulatory strategy, and site monitoring across international jurisdictions.",
"price": "Custom CRO contract",
"note": "",
"url": "ethicacro.com"
},
{
"id": "CR-07",
"name": "Cedar Clinical Research (Numinus subsidiary)",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "KAP/psilocybin/LSD/MDMA trial site — MindMed Phase II site",
"svc": "Clinical research site and CRO (formerly Novamind; now a Numinus subsidiary) running ketamine, psilocybin, LSD, and MDMA trials. Selected as a clinical site for a MindMed Phase II trial.",
"price": "Custom research partnership",
"note": "",
"url": "numinusnetwork.com"
},
{
"id": "CR-08",
"name": "iNGENu CRO",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Dedicated psychedelic/cannabinoid CRO — Australia/APAC",
"svc": "Australian full-service CRO working exclusively in the cannabinoid and psychedelic space. CRO for Lobe Sciences psilocin analogue trials and Psyence Biomed Phase IIb psilocybin palliative-care trial in Melbourne.",
"price": "Custom CRO contract",
"note": "",
"url": "ingenucro.com/cannabinoid-psychedelic"
},
{
"id": "CR-09",
"name": "CMAX Clinical Research",
"tier": "TIER 1",
"cat": "Clinical Research Orgs",
"sub": "Phase I-II site — MycoMedica psilocybin trials, Adelaide",
"svc": "Adelaide-based Phase I and Phase II clinical trials unit serving as the site for MycoMedica Life Sciences psilocybin (MLS101) trials (NCT06326606, NCT06643637; PI Sepehr Shakib).",
"price": "Custom site agreement",
"note": "",
"url": "cmax.com.au"
},
{
"id": "CR-10",
"name": "MAC Clinical Research",
"tier": "TIER 2",
"cat": "Clinical Research Orgs",
"sub": "One of Europe's largest CRO networks — UK/Europe",
"svc": "UK-based CRO with one of the largest clinical trial networks in Europe. Has documented active interest and capacity in psychedelic-compound trials. Extensive Phase I-III infrastructure across psychiatry and neuroscience.",
"price": "Custom CRO contract",
"note": "Psychedelic trial not yet named; Tier 2 pending confirmation",
"url": "macplc.com"
},
{
"id": "HR-01",
"name": "DanceSafe",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "Drug checking / reagent kits / fentanyl strips — US/Canada chapters",
"svc": "501(c)(3) public-health organization founded 1998 by Emanuel Sferios. Provides drug checking, reagent test kits, fentanyl test strips, and peer education at nightlife events and festivals. Chapters across the US and Canada.",
"price": "Free services; kits available for purchase",
"note": "",
"url": "dancesafe.org"
},
{
"id": "HR-02",
"name": "Zendo Project (a MAPS Project)",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "Psychedelic peer support / trip-sitting at festivals + events",
"svc": "MAPS-run psychedelic peer support organization providing safe-space trip-sitting services at festivals and events worldwide. Offers sitter training and integration support resources. Pioneered the structured psychedelic peer support model.",
"price": "Free services; training fees apply",
"note": "",
"url": "zendoproject.org"
},
{
"id": "HR-03",
"name": "Fireside Project",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "Free Psychedelic Peer Support Line — 14,000+ calls, 300 volunteers",
"svc": "Free Psychedelic Peer Support Line (call or text 62-FIRESIDE) for people during or integrating psychedelic experiences. Launched April 2021. Has received 14,000+ calls, trained 300+ volunteers, and provided 30,000+ hours of support.",
"price": "Free to callers",
"note": "",
"url": "firesideproject.org"
},
{
"id": "HR-04",
"name": "The Loop",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "UK's first drug-checking charity — FTIR analysis at festivals",
"svc": "UK's first dedicated drug-checking charity co-founded by Prof. Fiona Measham. Provides FTIR spectrometry and reagent drug analysis at UK festivals and city clinics. Has analyzed thousands of samples confirming widespread adulterants.",
"price": "Free to service users",
"note": "",
"url": "wearetheloop.org"
},
{
"id": "HR-05",
"name": "KnowYourStuffNZ",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "New Zealand publicly funded drug-checking — Bruker FTIR, Wendy Allison",
"svc": "New Zealand's legal, publicly funded drug-checking service founded by Wendy Allison. Uses Bruker FTIR spectrometry and TICTAC spectral library. Testing at events since 2015. Expanded to fixed-site clinics under New Zealand's Drug and Substance Checking Legislation Act 2021.",
"price": "Free to service users",
"note": "",
"url": "knowyourstuff.nz"
},
{
"id": "HR-06",
"name": "Energy Control (ABD)",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "International drug-checking — Spain, mail-in service, TEDI network",
"svc": "Spain-based international drug-checking and analysis service operated by ABD. Provides both in-person and international mail-in drug testing services. Part of the trans-European TEDI (Trans European Drug Information) network.",
"price": "Small fee for mail-in service",
"note": "",
"url": "energycontrol-international.org"
},
{
"id": "HR-07",
"name": "Erowid",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "Nonprofit psychoactive substance information — non-judgmental, global",
"svc": "Member-supported nonprofit providing reliable, evidence-based, and non-judgmental information about psychoactive substances. Operates a comprehensive drug information library covering pharmacology, safety, legal status, and subjective reports.",
"price": "Free",
"note": "",
"url": "erowid.org"
},
{
"id": "HR-08",
"name": "N.E.S.T. — Network of Emotional Support Teams",
"tier": "TIER 1",
"cat": "Harm Reduction",
"sub": "In-person psychedelic harm reduction + training — California",
"svc": "California-based harm reduction organization providing in-person psychedelic harm reduction services at events and festivals, advanced harm-reduction professional training, and peer support certification.",
"price": "Contact for training program fees",
"note": "",
"url": "nestharmreduction.com"
},
{
"id": "HR-09",
"name": "Bunk Police",
"tier": "TIER 2",
"cat": "Harm Reduction",
"sub": "Reagent test-kit manufacturer/distributor — global retail",
"svc": "Manufacturer and distributor of drug reagent test kits used at festivals, events, and at home to verify substance identity and detect adulterants in psychedelics and other substances. Products include Marquis, Mecke, Mandelin, and Froehde reagents.",
"price": "$5-$30 per kit",
"note": "",
"url": "bunkpolice.com"
},
{
"id": "HR-10",
"name": "Bluelight",
"tier": "TIER 2",
"cat": "Harm Reduction",
"sub": "International online harm reduction community/forum",
"svc": "International peer harm reduction forum and community providing substance-specific discussion, experience reports, and dosage information across psychedelics and other drug categories.",
"price": "Free",
"note": "",
"url": "bluelight.org"
},
{
"id": "HR-11",
"name": "Crew 2000 Scotland",
"tier": "TIER 2",
"cat": "Harm Reduction",
"sub": "Scottish drug-checking and harm reduction org",
"svc": "Edinburgh-based harm reduction organization providing drug information, testing, and outreach services across Scotland. Runs drug-checking services at events and operates a helpline for safer drug use guidance.",
"price": "Free services",
"note": "",
"url": "crew.scot"
},
{
"id": "HR-12",
"name": "Jellinek",
"tier": "TIER 2",
"cat": "Harm Reduction",
"sub": "Netherlands drug-checking and treatment org",
"svc": "Netherlands-based drug-checking service and addiction treatment organization. Provides substance analysis in partnership with festivals and event organizers. Part of the broader European harm reduction infrastructure referenced by the TEDI network.",
"price": "Free to service users",
"note": "",
"url": "jellinek.nl"
},
{
"id": "IC-01",
"name": "Chacruna Institute for Psychedelic Plant Medicines",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Sacred plant advocacy — Bia Labate, Council for Protection of Sacred Plants",
"svc": "Founded by anthropologist Bia Labate. Runs the Council for the Protection of Sacred Plants. Published the RFRA and Best Practices Guide for psychedelic plant medicine churches. Files amicus briefs in federal RFRA cases. Leading academic and advocacy bridge between indigenous practice and psychedelic policy.",
"price": "Nonprofit",
"note": "",
"url": "chacruna.net"
},
{
"id": "IC-02",
"name": "Indigenous Peyote Conservation Initiative (IPCI)",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "605-acre peyote preserve — Texas, Miriam Volat exec. dir.",
"svc": "Formed 2017 by the National Council of Native American Churches. Operates a 605-acre peyote preserve and spiritual homesite in Hebbronville, Texas. Indigenous-led peyote conservation and access program addressing severe depletion of wild peyote habitat.",
"price": "Nonprofit",
"note": "",
"url": "ipci.life"
},
{
"id": "IC-03",
"name": "National Council of Native American Churches (NCNAC)",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Coalition of NAC bodies — peyote policy governance",
"svc": "Coalition of the Native American Church of Oklahoma, NAC of South Dakota, NAC of North America, and Azee Bee Nahagha of Dine Nation. Governs Indigenous peyote policy at the national level. Formally requests peyote be excluded from decriminalization measures.",
"price": "Nonprofit",
"note": "",
"url": ""
},
{
"id": "IC-04",
"name": "Native American Rights Fund (NARF)",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Peyote access + sacred land legal support since 1983",
"svc": "Boulder-based nonprofit legal organization providing legal support to Native American Church members on peyote access, sacred land rights, and water rights since 1983. Senior attorney Steve Moore has handled dozens of peyote-related matters.",
"price": "Pro bono / nonprofit legal services",
"note": "",
"url": "narf.org"
},
{
"id": "IC-05",
"name": "Sacred Plant Alliance",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Self-regulating practitioner council — co-amicus in Iowaska federal case",
"svc": "Self-regulating professional council of entheogenic practitioners maintaining standards of conduct and spiritual accountability. Co-filed an amicus brief with Chacruna Institute in the Iowaska Church of Healing federal RFRA appeal.",
"price": "Membership-based",
"note": "",
"url": "sacredplantalliance.org"
},
{
"id": "IC-06",
"name": "Church of the Eagle and the Condor",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Landmark RFRA settlement with DEA — sacramental ayahuasca use",
"svc": "Arizona ayahuasca church that reached a landmark Religious Freedom Restoration Act settlement with the US government allowing sacramental ayahuasca use. One of the first US ayahuasca churches to secure explicit federal accommodation.",
"price": "Church",
"note": "",
"url": ""
},
{
"id": "IC-07",
"name": "Uniao do Vegetal (UDV)",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Unanimous SCOTUS RFRA exemption — Gonzales v. O Centro, 2006",
"svc": "Brazilian ayahuasca church with a unanimous US Supreme Court RFRA exemption (8-0 decision by Chief Justice Roberts in Gonzales v. O Centro Espírita Beneficente União do Vegetal, 546 U.S. 418 (2006)). The foundational RFRA precedent for religious sacramental use of scheduled substances.",
"price": "Church",
"note": "",
"url": "udv.org.br"
},
{
"id": "IC-08",
"name": "Santo Daime",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Established US RFRA exemption — Oregon federal case",
"svc": "Brazilian ayahuasca church with an established US RFRA exemption secured through an Oregon federal district court case. Santo Daime communities operate in the US under federal religious freedom protections allowing sacramental use of ayahuasca.",
"price": "Church",
"note": "",
"url": ""
},
{
"id": "IC-09",
"name": "Indigenous Reciprocity Initiative of the Americas",
"tier": "TIER 1",
"cat": "Indigenous / Ceremonial",
"sub": "Chacruna reciprocity program — supporting plant medicine communities",
"svc": "Reciprocity and donation channel operated by Chacruna Institute supporting Indigenous plant medicine communities whose traditional practices have contributed to the modern psychedelic ecosystem.",
"price": "Nonprofit",
"note": "",
"url": "chacruna.net"
},
{
"id": "IC-10",
"name": "Soul Quest Ayahuasca Church",
"tier": "TIER 2",
"cat": "Indigenous / Ceremonial",
"sub": "Protracted DEA litigation — RFRA exemption pending; Florida",
"svc": "Florida-based ayahuasca church in protracted federal litigation with the DEA over a CSA religious exemption under RFRA. Currently operating while legal proceedings continue.",
"price": "Retreat fees apply",
"note": "RED FLAG: Contested legal status; participant death reported — verify independently before engagement",
"url": "soulquestayahuasca.com"
},
{
"id": "RC-01",
"name": "Epic Healing Eugene",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Oregon — first licensed US psilocybin service center",
"svc": "The first legally licensed psilocybin service center in the United States, located in Eugene, Oregon. Licensed under Oregon Measure 109. Provides licensed psilocybin administration sessions with trained licensed facilitators.",
"price": "Contact for session pricing",
"note": "",
"url": "epichealingeugene.com"
},
{
"id": "RC-02",
"name": "Chariot",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Oregon + Colorado licensed — Portland and Boulder",
"svc": "Oregon-licensed psilocybin service center (Portland) and Colorado-licensed natural medicine healing center (Chariot Boulder). Dual-state licensed operation providing legal psilocybin facilitation services under Measure 109 and the Colorado Natural Medicine Health Act.",
"price": "Contact for session pricing",
"note": "",
"url": "chariotspace.com"
},
{
"id": "RC-03",
"name": "Oregon OHA Psilocybin Licensee Directory",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Official Oregon licensee registry — authoritative full list",
"svc": "Oregon Health Authority official directory of all licensed psilocybin service centers, manufacturers, laboratories, and facilitators under Measure 109. The authoritative, current source for all Oregon-licensed service centers. Updated regularly as new licenses are issued.",
"price": "Free public directory",
"note": "Re-verify quarterly — new licenses issued regularly",
"url": "oregon.gov/oha/ph/preventionwellness/pages/psilocybin-licensee-directory.aspx"
},
{
"id": "RC-04",
"name": "Colorado DORA Natural Medicine Registry",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Official Colorado licensed healing centers registry",
"svc": "Colorado Department of Regulatory Agencies official registry of all licensed natural medicine healing centers, facilitators, and testing laboratories under Proposition 122. The authoritative source for all Colorado-licensed service providers.",
"price": "Free public directory",
"note": "Re-verify quarterly — licensing opened December 2024",
"url": "dpo.colorado.gov/NaturalMedicine"
},
{
"id": "RC-05",
"name": "Beckley Retreats",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Jamaica + Netherlands — psilocybin, Beckley Foundation lineage",
"svc": "Multi-day legal psilocybin retreats in Jamaica and the Netherlands. Founded 2021 on the research lineage of the Beckley Foundation (Amanda Feilding). Structured preparation, ceremony, and integration protocol. Evidence-based approach drawing on decades of psychedelic research.",
"price": "$3,000-$6,000+ per retreat",
"note": "",
"url": "beckleyretreats.com"
},
{
"id": "RC-06",
"name": "MycoMeditations",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Jamaica — Treasure Beach, long-running psilocybin retreats",
"svc": "One of the earliest and longest-running legal psilocybin mushroom retreat operations, located at Treasure Beach, Jamaica. Multiple retreat formats from solo to group. Medically screened intake.",
"price": "$3,000-$5,000 per retreat",
"note": "",
"url": "mycomeditations.com"
},
{
"id": "RC-07",
"name": "Atman Retreat",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Jamaica — legal psilocybin mushroom retreats",
"svc": "Jamaica-based legal psilocybin mushroom retreat center offering structured preparation, guided ceremony, and integration support. Medical screening included. Small-group and private retreat formats.",
"price": "Contact for current pricing",
"note": "",
"url": "atmanretreat.com"
},
{
"id": "RC-08",
"name": "Soltara Healing Center",
"tier": "TIER 1",
"cat": "Retreat Centers",
"sub": "Costa Rica — ayahuasca with Shipibo healers, max 20 guests",
"svc": "Nicoya Peninsula, Costa Rica ayahuasca retreat center working with traditional Shipibo healers. Maximum 20 guests per retreat for intimate ceremonial environment. Extended preparation and integration support.",
"price": "$3,500-$6,000 per retreat",
"note": "",
"url": "soltara.co"
},
{
"id": "RC-09",
"name": "Evolute Institute",
"tier": "TIER 2",
"cat": "Retreat Centers",
"sub": "Netherlands — legal psilocybin truffle retreats",
"svc": "Netherlands-based psilocybin truffle retreat center operating legally under Dutch law. Provides structured retreat experiences with preparation, guided sessions, and integration. Focuses on executive and leadership audiences.",
"price": "2,500-4,000 EUR per retreat",
"note": "",
"url": "evoluteinstitute.com"
},
{
"id": "RC-10",
"name": "Alalaho Retreats",
"tier": "TIER 2",
"cat": "Retreat Centers",
"sub": "Netherlands — legal psilocybin truffle retreats",
"svc": "Netherlands psilocybin truffle retreat center offering group and private retreat formats under Dutch legal framework. Preparation and integration included.",
"price": "Contact for current pricing",
"note": "",
"url": "alalaho.com"
},
{
"id": "RC-11",
"name": "Rythmia Life Advancement Center",
"tier": "TIER 2",
"cat": "Retreat Centers",
"sub": "Costa Rica — ayahuasca resort; verify medical-license claim",
"svc": "Ayahuasca resort in Guanacaste, Costa Rica. Claims to be a medically licensed plant medicine facility. Offers multiple ayahuasca ceremonies over week-long stays with adjunct therapies and wellness programming.",
"price": "$5,000-$10,000 per week",
"note": "RED FLAG: Verify medical-license claim independently",
"url": "rythmia.com"
},
{
"id": "RC-12",
"name": "Beond Ibogaine",
"tier": "TIER 2",
"cat": "Retreat Centers",
"sub": "Cancun Mexico — cardiac-monitored medical ibogaine",
"svc": "Ibogaine treatment center in Cancun, Mexico operating a medical model with cardiac monitoring (12-lead ECG) and on-site medical staff. Focuses on addiction interruption and neurological reset protocols. Cardiac safety infrastructure is the baseline standard for responsible ibogaine administration.",
"price": "$6,000-$15,000 per program",
"note": "Ibogaine carries cardiac risk; cardiac monitoring required",
"url": "beondibogaine.com"
},
{
"id": "RC-13",
"name": "Sanctuary Tulum",
"tier": "TIER 3",
"cat": "Retreat Centers",
"sub": "Mexico — ibogaine + ayahuasca; verify safety claims",
"svc": "Tulum, Mexico retreat center offering ibogaine and ayahuasca programs with claimed medical screening and adjunct therapy components.",
"price": "Contact for pricing",
"note": "RED FLAG: Superlative marketing — verify medical claims and safety protocols independently",
"url": "sanctuarytulum.com"
},
{
"id": "RC-14",
"name": "Sayulita Wellness Retreat",
"tier": "TIER 3",
"cat": "Retreat Centers",
"sub": "Mexico — psilocybin mushroom and ibogaine retreats",
"svc": "Sayulita, Mexico retreat center offering psilocybin mushroom and ibogaine retreat programs. Medical screening required for ibogaine.",
"price": "Contact for pricing",
"note": "Tier 3 — verify independently",
"url": "sayulitawellnessretreat.com"
},
{
"id": "MW-01",
"name": "Psychedelic Alpha — Job Board",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "Industry job board — biotech/pharma/clinical/policy/advocacy",
"svc": "Psychedelic Alpha dedicated job board covering positions across the entire psychedelic ecosystem: biotech and pharmaceutical companies, clinical research organizations, policy organizations, care delivery providers, and advocacy groups.",
"price": "Free to job seekers; listing fees for employers",
"note": "",
"url": "jobs.psychedelicalpha.com"
},
{
"id": "MW-02",
"name": "Work in Psychedelics",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "Dedicated psychedelic industry job board — global",
"svc": "Dedicated job board exclusively focused on the psychedelic industry. Lists positions across research, clinical, business development, communications, and operations roles at psychedelic companies, nonprofits, and research institutions worldwide.",
"price": "Free to job seekers",
"note": "",
"url": "workinpsychedelics.com"
},
{
"id": "MW-03",
"name": "Psychedelic Support",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "Credentialed therapist/MD/integration consultant directory",
"svc": "National network and directory of licensed therapists, MDs, and integration consultants with verified psychedelic experience. Providers must be licensed healthcare professionals or experienced psychedelic-trial guides. Also hosts accredited continuing education courses.",
"price": "Free to clients; provider membership fees",
"note": "",
"url": "psychedelic.support"
},
{
"id": "MW-04",
"name": "Fluence Therapist Directory",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "Fluence-certified psychedelic therapist directory",
"svc": "Searchable directory making Fluence-certified psychedelic therapists discoverable to prospective clients and employers. Includes certification type, modality specialty, location, and telehealth availability.",
"price": "Free to clients; included in Fluence certification",
"note": "",
"url": "fluencetraining.com"
},
{
"id": "MW-05",
"name": "Journey Clinical",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "In-house medical team + KAP platform for licensed psychotherapists",
"svc": "Platform providing an in-house medical team enabling licensed psychotherapists to build ketamine-assisted psychotherapy practices. Covers patient eligibility assessment, ketamine prescriptions, and outcome monitoring. Research collaboration with COMPASS Pathways.",
"price": "Platform fee + patient costs",
"note": "",
"url": "journeyclinical.com"
},
{
"id": "MW-06",
"name": "Mindbloom",
"tier": "TIER 1",
"cat": "Mental Health Workforce & Staffing",
"sub": "At-home KAP platform — 600,000+ sessions in 38 states",
"svc": "At-home ketamine therapy platform reporting nearly 600,000 ketamine therapy sessions facilitated in 38 states since 2019. Employs and contracts clinicians and prescribers at scale. Published an 11,441-client real-world efficacy study in the Journal of Affective Disorders.",
"price": "Program fees starting ~$1,000/month",
"note": "",
"url": "mindbloom.com"
},
{
"id": "MW-07",
"name": "Better U",
"tier": "TIER 2",
"cat": "Mental Health Workforce & Staffing",
"sub": "At-home KAP provider — hires clinical directors/therapists",
"svc": "At-home ketamine therapy provider offering KAP telehealth services across US states. Hires clinical directors, therapists, and prescribers. Structured around guided at-home ketamine sessions with licensed therapist support.",
"price": "Contact for provider partnership rates",
"note": "",
"url": "betterucare.com"
},
{
"id": "MW-08",
"name": "Almadelic",
"tier": "TIER 2",
"cat": "Mental Health Workforce & Staffing",
"sub": "KAP telehealth platform recruiting therapists + prescribers",
"svc": "KAP telehealth platform recruiting licensed therapists and prescribers to provide ketamine-assisted psychotherapy services. Platform-based model connecting credentialed providers with patients.",
"price": "Contact for provider partnership rates",
"note": "",
"url": "almadelic.com"
},
{
"id": "MW-09",
"name": "Anywhere Clinic",
"tier": "TIER 2",
"cat": "Mental Health Workforce & Staffing",
"sub": "KAP staffing/telehealth — remote US",
"svc": "Remote US ketamine-assisted therapy provider operating a telehealth staffing model. Recruits licensed therapists and prescribers for remote KAP delivery.",
"price": "Contact for provider partnership rates",
"note": "",
"url": "anywhereclinic.com"
},
{
"id": "MW-10",
"name": "Intrepid Therapy Collective",
"tier": "TIER 2",
"cat": "Mental Health Workforce & Staffing",
"sub": "KAP staffing/telehealth — remote US",
"svc": "Remote ketamine-assisted psychotherapy collective recruiting licensed therapists for structured KAP delivery. Collective model providing peer support, shared protocols, and flexible scheduling for KAP clinicians.",
"price": "Contact for collective membership",
"note": "",
"url": "intrepidtherapy.com"
},
{
"id": "AR-01",
"name": "Johns Hopkins Center for Psychedelic & Consciousness Research",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Flagship US academic psychedelic research center — launched 2019",
"svc": "The leading US academic psychedelic research center. Conducts landmark clinical trials on psilocybin for depression, addiction, and end-of-life distress. Co-PIs Matthew Johnson and Roland Griffiths (d. 2023). Offers a Psychedelic Science and Medicine Coursera course.",
"price": "Research institution",
"note": "",
"url": "hopkinsmedicine.org"
},
{
"id": "AR-02",
"name": "NYU Langone Center for Psychedelic Medicine",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Est. 2021 — Michael Bogenschutz, tri-institutional consortium",
"svc": "Established 2021. Director Michael Bogenschutz. Psilocybin trials for alcohol use disorder and MDMA for PTSD. Part of a tri-institutional psychiatric training consortium with Yale School of Medicine and Johns Hopkins.",
"price": "Research institution",
"note": "",
"url": "med.nyu.edu"
},
{
"id": "AR-03",
"name": "UC Berkeley Center for the Science of Psychedelics (BCSP)",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Michael Silver, UC Berkeley — research + facilitation training",
"svc": "UC Berkeley interdisciplinary center led by Michael Silver. Conducts psychedelic science research in collaboration with Imperial College London and other global partners. Also operates the 9-month Certificate in Psychedelic Facilitation training program.",
"price": "Research institution",
"note": "",
"url": "psychedelics.berkeley.edu"
},
{
"id": "AR-04",
"name": "Imperial College London — Centre for Psychedelic Research",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "World's first psychedelic research center — David Erritzoe clinical director",
"svc": "The first dedicated psychedelic research center globally, founded at Imperial College London. Built on the Nutt/Carhart-Harris research lineage. Clinical director David Erritzoe. Neuroimaging-focused research on psilocybin, DMT, MDMA, and other compounds.",
"price": "Research institution",
"note": "",
"url": "imperial.ac.uk/psychedelic-research-centre"
},
{
"id": "AR-05",
"name": "Yale Program for Psychedelic Science",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Pittenger & Kelmendi — psilocybin for OCD since 2016",
"svc": "Yale Department of Psychiatry psychedelic research program co-directed by Christopher Pittenger and Benjamin Kelmendi. Psilocybin for OCD research group formed 2016. Part of the NYU tri-institutional consortium.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-06",
"name": "Stanford Psychedelic Science Group",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Ketamine/MDMA/psilocybin — neuroscience + psychiatry, Stanford",
"svc": "Stanford interdisciplinary psychedelic science group spanning neuroscience, psychiatry, and anesthesiology. Research covers ketamine mechanisms, MDMA neuroscience, and psilocybin therapeutic effects across Stanford School of Medicine departments.",
"price": "Research institution",
"note": "",
"url": "med.stanford.edu/spsg"
},
{
"id": "AR-07",
"name": "MGH/Harvard — Center for the Neuroscience of Psychedelics",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Launched 2021 — Harvard Medical School collaboration",
"svc": "Massachusetts General Hospital center for psychedelic neuroscience research, launched 2021 in collaboration with Harvard Medical School. Focuses on neuroimaging, mechanistic neuroscience, and clinical translation of psychedelic compounds.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-08",
"name": "University of Michigan — Michigan Psychedelic Center",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Global Psychedelic Survey 2023/2025 — real-world experience data",
"svc": "University of Michigan Medical School psychedelic research center. Conducts the Global Psychedelic Survey (GPS) capturing real-world psychedelic use data from tens of thousands of participants (2023 and 2025 waves).",
"price": "Research institution",
"note": "",
"url": "michiganpsychedelic.med.umich.edu"
},
{
"id": "AR-09",
"name": "Maastricht University — Psychopharmacology Department",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Kim Kuypers — microdosing research, Netherlands",
"svc": "Maastricht University psychopharmacology department led by Kim Kuypers. Conducts rigorous laboratory studies on psilocybin, LSD, microdosing, and MDMA including placebo-controlled pharmacological experiments.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-10",
"name": "University of Zurich — Neuropsychopharmacology",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Vollenweider lineage — psilocybin/LSD neuroimaging, Switzerland",
"svc": "University of Zurich neuropsychopharmacology research program with decades of foundational psilocybin and LSD neuroimaging work (Franz Vollenweider lineage). Among the longest-running academic psychedelic research programs globally.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-11",
"name": "Leiden University Medical Center",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Netherlands — COMPASS Pathways collaboration",
"svc": "Leiden University Medical Center psychedelic research program with documented collaboration with COMPASS Pathways on psilocybin neuroimaging and clinical research. Part of the Dutch academic psychedelic research network.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-12",
"name": "University of Toronto — Psychedelic Studies Research Program",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Canada — leading Canadian academic psychedelic research",
"svc": "University of Toronto academic psychedelic research program. One of the leading Canadian academic centers for psychedelic science, covering clinical, pharmacological, and sociocultural dimensions.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-13",
"name": "CU Denver — Center for Psychedelic Research",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Transdisciplinary research + DORA facilitator training — launched 2024",
"svc": "University of Colorado Denver transdisciplinary Center for Psychedelic Research launched 2024. Dual role: original psychedelic research and a DORA-approved psilocybin facilitator training program. Combines academic research with direct practitioner preparation.",
"price": "Research institution",
"note": "",
"url": "clas.ucdenver.edu/psychedelic-research"
},
{
"id": "AR-14",
"name": "Harvard Divinity School — Center for the Study of World Religions",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Psychedelics & spirituality — NAC/peyote programming, Harvard",
"svc": "Harvard Center for the Study of World Religions hosts the Psychedelic Intersections conference series exploring psychedelics and spiritual practice. Native American Church and peyote programming central to curriculum.",
"price": "Research institution",
"note": "",
"url": "cswr.hds.harvard.edu"
},
{
"id": "AR-15",
"name": "UT Austin — McGill Center for Psychedelic Research & Therapy",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Dell Medical School — Austin, Texas",
"svc": "Charmaine and Gordon McGill Center for Psychedelic Research and Therapy at the University of Texas at Austin Dell Medical School. Academic clinical psychedelic research program in the south-central US.",
"price": "Research institution",
"note": "",
"url": ""
},
{
"id": "AR-16",
"name": "University of Exeter — Psychedelics Certificate",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "World's first postgraduate certificate in psychedelics — online",
"svc": "University of Exeter offers the world's first postgraduate certificate program in psychedelics. Eight-month online program (approximately GBP 4,200). Designed for healthcare professionals, researchers, and policymakers seeking academic grounding in psychedelic science.",
"price": "GBP 4,200 (~$5,300)",
"note": "",
"url": ""
},
{
"id": "AR-17",
"name": "Usona Institute",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Nonprofit clinical psilocybin research — Wisconsin",
"svc": "Wisconsin-based nonprofit conducting preclinical and clinical psilocybin research. Collaborates with leading academic institutions. Running a Phase 2 psilocybin trial for major depressive disorder. Committed to non-commercial development of psilocybin for medical use.",
"price": "Nonprofit/grant-funded",
"note": "",
"url": "usonainstitute.org"
},
{
"id": "AR-18",
"name": "Heffter Research Institute",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Pioneering nonprofit — funding psilocybin research since 1993",
"svc": "One of the founding nonprofit institutions of modern psychedelic research. Has funded or co-funded many of the landmark psilocybin studies at Johns Hopkins, NYU, and internationally since 1993.",
"price": "Nonprofit/grant-funded",
"note": "",
"url": "heffter.org"
},
{
"id": "AR-19",
"name": "Beckley Foundation",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "UK — Amanda Feilding, co-funded Imperial + Johns Hopkins studies",
"svc": "UK-based psychedelic research and drug policy reform organization founded and directed by Amanda Feilding. Co-funded and collaborated on landmark psilocybin studies at Imperial College London and Johns Hopkins University.",
"price": "Foundation/donor-funded",
"note": "",
"url": "beckleyfoundation.org"
},
{
"id": "AR-20",
"name": "OPEN Foundation",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Netherlands — psychedelic science conferences + research network",
"svc": "Netherlands-based nonprofit advancing psychedelic science through conferences, research funding, and network building. Organizes the Interdisciplinary Conference on Psychedelic Research (ICPR), one of the leading global academic psychedelic science conferences.",
"price": "Nonprofit",
"note": "",
"url": "open-foundation.org"
},
{
"id": "AR-21",
"name": "ICEERS — International Center for Ethnobotanical Education, Research & Service",
"tier": "TIER 1",
"cat": "Academic Research Centers",
"sub": "Spain/global — ayahuasca/iboga/plant medicine research + legal defense",
"svc": "Spain-based international research and legal nonprofit focused on ayahuasca, iboga, and traditional plant medicines. Provides legal defense support for plant medicine practitioners, conducts ethnobotanical research, and maintains global databases on traditional plant use.",
"price": "Nonprofit",
"note": "",
"url": "iceers.org"
}
];

export default async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  const pin = req.headers['x-admin-pin'] || (req.query && req.query.pin);
  if (pin !== ADMIN_PIN) {
    return res.status(401).json({ error: 'Unauthorized' });
  }
  return res.status(200).json({ ok: true, count: LISTINGS.length, listings: LISTINGS });
}
